minisite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

from expenselogger import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    #implemented directly in project root to avoid using expenselogger namespace
    url(r'^create/', views.create_expense, name='create'), 
    url(r'^admin/', include(admin.site.urls)),
)

expenselogger/models.py
from django.db import models
from django.core import serializers

class Expense(models.Model):
	# choices for expense type fields
	EXPENSE_TYPES = ( 
		('F','Flight'),
		('C','Car Rental'),
		('H','Hotel'), )

	# table attributes
	name = models.CharField(max_length=100)
	expense_type = models.CharField(max_length=1, choices=EXPENSE_TYPES)
	amount = models.DecimalField(max_digits=7, decimal_places=2)
	date = models.DateField()

	# string representation as expense name
	def __unicode__(self):
		return self.name

	def to_json(self):
		return serializers.serialize('json', [self]);

expenselogger/forms.py
from django.forms import ModelForm
from expenselogger.models import Expense

class ExpenseForm(ModelForm):
	class Meta:
		model = Expense
		fields = ['name', 'expense_type', 'amount', 'date']

expenselogger/views.py
from expenselogger.models import Expense
from django.shortcuts import render
from django.http import HttpResponseRedirect
from expenselogger.forms import ExpenseForm



def index(request):

    # get context for all expenses from helper
    context = all_expense_context_helper()

    # add blank form
    context['form'] = ExpenseForm()
    
    return render(request, 'expenselogger/index.html', context)
    
# post to create expenses
def create_expense(request):
	form = ExpenseForm(request.POST or None)
	if form.is_valid():
		expense = form.save()
		return HttpResponseRedirect('/')
	else:
		# get context of all expenses to support list below form
		context = all_expense_context_helper()
		# add form
		context['form'] = form

		#redisplay with error
		return render(request, 'expenselogger/index.html', context)


# helper function to get context for all expenses
def all_expense_context_helper():
	expense_list = Expense.objects.all().order_by('-date')

	return {'expense_list': expense_list}

expenselogger/templates/expenselogger/index.html
{% extends "expenselogger/main.html" %}

{% block content %}
<h2>Submit New Expense</h2>

<form id="expenseform" action="/create/" method="post" class="form-horizontal" >
    {% csrf_token %}
    {% for field in form %}
        <div class="form_group row">
            {{ field.errors }}
            <div class="col-sm-2">
    	        {{ field.label_tag }} 
    	    </div>
    	    <div class="col-sm-10">
    	        {{ field }}
       		</div>
        </div>
    {% endfor %}
    <button type="submit" value="Submit" class="btn btn-default">Submit</button>

</form>



<h2>Recently Submitted Expenses</h2>

<table class="table table-hover">
    <thead>
        <!-- header row -->
        <th>Date</th>
        <th>Expense Name</th>
        <th>Type</th>
        <th>Amount</th>
    </thead>
    {% for expense in expense_list %}
        <tr id="expense_{{ forloop.counter }}" class="expense" 
                data-expense='{{ expense.to_json|safe }}' >
            <td class="expense_date">{{ expense.date }}</td>
            <td class="expense_name">{{ expense.name }}</td>
            <td class="expense_type">{{ expense.get_expense_type_display }}</td>
            <td class="expense_amount">{{ expense.amount|floatformat:"2" }}</td>
        </tr>
    {% endfor %}
</table>

{% endblock %}

expenselogger/templates/expenselogger/main.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
    <title>Expense Logger</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script type="text/javascript" src="{% static 'jquery-1.10.2.min.js' %}"></script> 
    <script type="text/javascript" src="{% static 'bootstrap.min.js' %}"></script> 
    <script type="text/javascript" src="{% static 'bootbox.min.js' %}"></script> 
</head>
<body>
	<h1><a href="{% url 'index' %}">Expense Logger</a></h1>
	{% block content %}
	{% endblock %}
	<script type="text/javascript" src="{% static 'expenses.js' %}"></script> 
</body>
</html>